[package]
name = "md5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.6"
rust-crypto = "0.2.36"
wild = "2.0.4"